spring.application.name=bookstore
spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:mysql://localhost:3306/bookstore
spring.datasource.username=root
spring.datasource.password=MauroLara2005

url=http://localhost:${server.port}